import { ethers } from 'ethers';
import { DEducationContractAddress as address } from "@app/const/contract.const";

const abi = [{"inputs":[{"internalType":"contract MinimalForwarder","name":"forwarder","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"_classroom","type":"string"},{"indexed":false,"internalType":"string","name":"_hashcode","type":"string"}],"name":"AddNewTranscriptForClass","type":"event"},{"anonymous":false,"inputs":[{"components":[{"internalType":"address","name":"StudentAddress","type":"address"},{"internalType":"string","name":"Classroom","type":"string"},{"internalType":"string","name":"HashCode","type":"string"}],"indexed":false,"internalType":"struct DEducation.StudentTranscript[]","name":"_studentTranscripts","type":"tuple[]"}],"name":"AddNewTranscriptForStudents","type":"event"},{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"string","name":"","type":"string"}],"name":"TranscriptForClass","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"address","name":"","type":"address"},{"internalType":"string","name":"","type":"string"}],"name":"TranscriptForStudents","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_classroom","type":"string"},{"internalType":"string","name":"_hashcode","type":"string"}],"name":"addNewTranscriptForClass","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"components":[{"internalType":"address","name":"StudentAddress","type":"address"},{"internalType":"string","name":"Classroom","type":"string"},{"internalType":"string","name":"HashCode","type":"string"}],"internalType":"struct DEducation.StudentTranscript[]","name":"_studentTranscripts","type":"tuple[]"}],"name":"addNewTranscriptForStudents","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"forwarder","type":"address"}],"name":"isTrustedForwarder","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}]
;

export function createInstance(provider: any) {
  return new ethers.Contract(address, abi, provider);
}
